#!/bin/bash

set -xeo pipefail

rm ./output/* || true
docker build -t render-transition .
docker run \
    -v ./output:/app/storage/images/ \
    -v ./tmp/:/tmp/ \
    --rm -it \
    render-transition
